# Example only. Do NOT commit real credentials.
# Create a real Secret named `todo-api-runtime` in namespace `flux-system`
# via your secret management flow (recommended: SOPS + Key Vault or External Secrets).
apiVersion: v1
kind: Secret
metadata:
  name: todo-api-runtime
  namespace: flux-system
type: Opaque
stringData:
  values.yaml: |
    env:
      - name: MONGODB_URI
        value: "mongodb://<username>:<password>@<host>:27017/?tls=true"
